# Generated by Django 6.1.1 on 2026-09-02 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_cellphone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=30)),
                ('cpf_person', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('register_date', models.DateTimeField(verbose_name='Item Register Date')),
                ('withdraw_date', models.DateTimeField(blank=True, null=True, verbose_name='Item Withdraw Date')),
                ('was_it_removed', models.BooleanField(verbose_name='Item Removed')),
                ('found_item_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_found', to='items.person')),
                ('owner_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_owned', to='items.person')),
            ],
        ),
    ]
