# Generated by Django 6.1.1 on 2026-09-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='was_it_removed',
        ),
    ]
