# Generated by Django 6.1.1 on 2026-09-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_was_it_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('lost', 'LOST'), ('found', 'FOUND'), ('returned', 'RETURNED')], default='lost', max_length=10),
        ),
    ]
